name: Deploy Dev

on:
  push:
    branches:
      - develop
      - feature/setup-dev
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses:  aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build image and push to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/deploy_dev/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/development/zwei-mis/web:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/development/zwei-mis/web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs/development/task-definition.json
          container-name: zwei-dev-container
          image: ${{ steps.login-ecr.outputs.registry }}/development/zwei-mis/web:${{ github.sha }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: zwei-dev-service
          cluster: zwei-dev-cluster